### ISSUE TITLE
In the new version toRaw() is replaced by rawValue

### ISSUE THREAD

**Issue by JetQin** [fullstackio/FlappySwift#33]
override func supportedInterfaceOrientations() -> Int {
        if UIDevice.currentDevice().userInterfaceIdiom == .Phone {
            return Int(UIInterfaceOrientationMask.AllButUpsideDown.rawValue)
        } else {
            return Int(UIInterfaceOrientationMask.All.rawValue)
        }
    }

**Comment by Modroid** [comment]
works great :+1:

**Comment by jashmenn** [comment]
fixed in d239eb917cb40
