### ISSUE TITLE
error in GameScene.swift

### ISSUE THREAD

**Issue by lhlpasser** [fullstackio/FlappySwift#44]
/FlappySwift-master/FlappyBird/GameScene.swift:206:19: Overriding method with selector 'touchesBegan:withEvent:' has incompatible type '(NSSet, UIEvent) -> ()'

**Comment by lhlpasser** [comment]
issue fixed.

override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {....}

**Comment by azpery** [comment]
FlappyBird/GameScene.swift:206:41: Reference to generic type 'Set' requires arguments in <...>
I get this error when I replace the code line

**Comment by MaddTheSane** [comment]
You have to tell Swift what the `Set` type is. In this case, I think it's just `Set<AnyObject>`.

**Comment by azpery** [comment]
It was indeed expecting Set<NSObject> thanks :) 
But now i've got an error In AppDelegate.swift with the function didFinishLaunchingWithOption.. I believe it expects something more. 

Edit: I Just deleted the function to resolve it ^^

**Comment by stoneyzhang** [comment]
@azpery  how did u solve this issue? i still have error as  "FlappyBird/GameScene.swift:206:41: Reference to generic type 'Set' requires arguments in <...>"

**Comment by azpery** [comment]
You have to tell what type the Set is : 
```javascript
Set<NSObject>
```

**Comment by jashmenn** [comment]
Fixed in 4e94e7bfe and friends
