### ISSUE TITLE
GameViewController.swift and 3 errors

### ISSUE THREAD

**Issue by stoneyzhang** [fullstackio/FlappySwift#48]
I have download the project, then use xcode 6.3.1 to open FlappyBird.xcodeproj

however, i have got the follow three errors, andy idea how to fix these issues?

FlappySwift-master/FlappyBird/GameScene.swift:206:19: Overriding method with selector 'touchesBegan:withEvent:' has incompatible type '(NSSet, UIEvent) -> ()'

FlappySwift-master/FlappyBird/GameViewController.swift:15:58: 'NSString' is not implicitly convertible to 'String'; did you mean to use 'as' to explicitly convert?

FlappySwift-master/FlappyBird/GameViewController.swift:34:36: 'UIView!' is not convertible to 'SKView'; did you mean to use 'as!' to force downcast?

thanks
email: stoney.zhang@qq.com

**Comment by remixnine** [comment]
I fixed the compilation errors in my fork. Here's the link: https://github.com/remixnine/FlappySwift/commits/master . Check out the fixes in my commits.

**Comment by stoneyzhang** [comment]
ok, thanks for ur reply

**Comment by jashmenn** [comment]
Fixed in 4e94e7bfe and friends
