### ISSUE TITLE
Auto Layout on different devices

### ISSUE THREAD

**Issue by hooman96** [fullstackio/FlappySwift#56]
Can we add auto lay out so that when we use different simulator like iPad, user can still play the game?

**Comment by jashmenn** [comment]
I love this idea

**Comment by pawurb** [comment]
Maybe I don't get it but in sprite kit you support different device sizes by scaling SKScene, not with autolayout. Anyway game seems to be working fine on both iphone and ipad simulators, I will close it then. @hooman96 please reopen if you think we can make some improvement here.
