### ISSUE TITLE
Black Bars on 4.7" and 5.5" screens

### ISSUE THREAD

**Issue by larsschwegmann** [fullstackio/FlappySwift#59]
There are black bars on the top and bottom of the screen on iPhone 6 and 6 plus. This is due to the lack of launch images for theses screen sizes.
Adding a launch image or using the new Launch Screen storyboards should fix the issue.
![bildschirmfoto 2015-10-03 um 23 23 21](https://cloud.githubusercontent.com/assets/1457934/10265186/cf97cab6-6a25-11e5-82a5-8992a03a82f3.png)

**Comment by pawurb** [comment]
Is already resolved on master, closing.
