### ISSUE TITLE
Bug on Device

### ISSUE THREAD

**Issue by leslie-wz** [fullstackio/FlappySwift#6]
Run on my iphone5 (iOS 7.1.1). Broke when the screen was still dark. Guess is the problem for SpriteKit since even initial game app written in Swift with SpriteKit can't work on device, while change to OC it works fine.

![flappybirdbug](https://cloud.githubusercontent.com/assets/1648124/3169360/bd165a0c-eb9a-11e3-8fe5-c20cb7d212fe.png)

**Comment by bandojulio** [comment]
@chenlam your fix stopped the crash but distorted the app graphics, did this happen to anyone?

**Comment by jashmenn** [comment]
I believe this is fixed now in ios8+
