### ISSUE TITLE
Error in Swift 3.0

### ISSUE THREAD

**Issue by kumarUjjawal** [fullstackio/FlappySwift#68]
![screen shot 2016-09-05 at 9 59 20 pm](https://cloud.githubusercontent.com/assets/10569915/18253644/16a9b87c-73b4-11e6-855c-83a7746e8262.png)
![screen shot 2016-09-05 at 9 59 33 pm](https://cloud.githubusercontent.com/assets/10569915/18253645/16aab380-73b4-11e6-8be7-031671703e42.png)
Getting these two errors in Swift 3.0 with Xcode beta 8.Please Fix this.

**Comment by DmitriyKirakosyan** [comment]
Use my fork while it is not merged.
