### ISSUE TITLE
Is this OK if I make some changes in the game & publish it to the AppStore?

### ISSUE THREAD

**Issue by UzumakiAlfredo** [fullstackio/FlappySwift#83]
Hi.
I don't know much about the Copyright thing, so please help me out here!
Is this OK if I make some changes in the game & publish it to the AppStore (for free)?
What should I do about Copyright?

**Comment by JandersonConstantino** [comment]
The current license is MIT.
You can make what you to want.

**Comment by JandersonConstantino** [comment]
The current license is MIT.
You can make what you do want.

**Comment by jashmenn** [comment]
Go for it
